#!/usr/bin/env python3
"""
Writes the SYNTHETIC process-framework workbooks used by the BicycleWorks
demonstration (fixtures/process_framework/). They are NOT APQC content:
node ids use a SYN- prefix, no external references are given, and every
workbook says so. Replace them with authorised APQC content or the
customer's own hierarchy for real use.

    python3 scripts/make_process_fixtures.py
"""

from __future__ import annotations

import os

from openpyxl import Workbook

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "fixtures", "process_framework")
LABEL = "SYNTHETIC demonstration fixture -- not APQC content, no official identifiers"

V1 = [
    ("SYN-1", "Plan and manage the business", "Category", ""),
    ("SYN-1.1", "Set the sales and operations plan", "Process group", ""),
    ("SYN-3", "Sell to dealers", "Category", ""),
    ("SYN-3.1", "Manage dealer accounts", "Process group", ""),
    ("SYN-3.2", "Process dealer orders", "Process group", ""),
    ("SYN-4", "Deliver bicycles", "Category", ""),
    ("SYN-4.1", "Plan warehouse work", "Process group", ""),
    ("SYN-4.2", "Ship dealer orders", "Process group", ""),
    ("SYN-5", "Manage dealer returns and after-sales", "Category", ""),
    ("SYN-5.1", "Authorise dealer returns", "Process group", ""),
    ("SYN-5.1.1", "Receive a return request from a dealer", "Process", "Dealer asks to send a bicycle back"),
    ("SYN-5.1.2", "Check return eligibility and warranty terms", "Process", ""),
    ("SYN-5.1.3", "Issue a return authorisation number", "Process", "No return is accepted without one"),
    ("SYN-5.2", "Receive and inspect returned bicycles", "Process group", ""),
    ("SYN-5.2.1", "Receive a returned bicycle against its authorisation", "Process", ""),
    ("SYN-5.2.2", "Inspect and classify the bicycle's condition", "Process",
     "Resaleable, repair required, damaged, warranty claim or scrap"),
    ("SYN-5.2.3", "Decide the disposition", "Process", "Return to stock, repair, warranty claim or scrap"),
    ("SYN-5.3", "Process warranty claims", "Process group", ""),
    ("SYN-6", "Manage finance", "Category", ""),
    ("SYN-6.1", "Process credits and value adjustments", "Process group", ""),
    ("SYN-6.1.1", "Issue a dealer credit for an accepted return", "Process", ""),
    ("SYN-6.1.2", "Post the inventory value adjustment", "Process", "Value impact of the return"),
    ("SYN-6.2", "Report financial performance", "Process group", ""),
    ("SYN-6.2.1", "Report returns by dealer, model and reason", "Process", "Monthly"),
    ("SYN-7", "Manage quality", "Category", ""),
    ("SYN-7.1", "Analyse return and defect trends", "Process group", ""),
]

# Version 2: one mapped node changes, one node is added, one unmapped node is removed.
V2 = [r for r in V1 if r[0] != "SYN-1.1"]
V2 = [("SYN-5.2.2", "Inspect, grade and photograph the bicycle's condition", "Process",
       "Grades A-D with photographs; classifications as before") if r[0] == "SYN-5.2.2" else r for r in V2]
V2.insert(V2.index(next(r for r in V2 if r[0] == "SYN-5.3")),
          ("SYN-5.2.4", "Move the bicycle to stock, repair or quarantine", "Process", ""))


def write(rows, name, note):
    wb = Workbook()
    ws = wb.active
    ws.title = "Framework"
    ws.append(["Node ID", "Parent ID", "Level", "Name", "Description", "Node type", "External reference"])
    for key, title, kind, desc in rows:
        parent = key.rsplit(".", 1)[0] if "." in key else ""
        ws.append([key, parent, key.count(".") + 1, title, desc, kind, ""])
    info = wb.create_sheet("About")
    for line in (LABEL, note, "Generated by scripts/make_process_fixtures.py for the Jade demonstration."):
        info.append([line])
    path = os.path.join(OUT, name)
    wb.save(path)
    print(path)


os.makedirs(OUT, exist_ok=True)
write(V1, "SYNTHETIC_bicycleworks_process_framework_v1.xlsx", "Version 1.")
write(V2, "SYNTHETIC_bicycleworks_process_framework_v2.xlsx",
      "Version 2: SYN-5.2.2 reworded, SYN-5.2.4 added, SYN-1.1 removed.")
