"""
Shared SQLite database for data that JsonFileStore's one-document-per-
file model doesn't fit: relational data (users <-> companies <->
roles <-> domain assignments, invitations) and Jira connections, which
move here from JsonFileStore in this same change.

Why SQLite, not a bigger database: nothing else in this project runs a
database server, and this is a prototype -- adding one would be new
infrastructure the current task explicitly doesn't call for. SQLite is
a single file, needs no server, and (like every other store this
service owns) lives under settings.data_dir, so it is covered by
whatever durable disk that already points at -- see config.py's own
comment on JDE_API_DATA_DIR. This is expected to be replaced, not
extended, when the project moves to Azure or another platform.

Why no ORM: every other persistence module in this codebase
(json_file_store.py) is a thin, direct wrapper with no framework
underneath it. sqlite3 is the same idea applied to relational data --
plain SQL, no mapper, nothing to configure.

Migrations: schema changes are numbered, append-only SQL blocks in
migrations.py, applied in order and recorded in schema_migrations
below. A fresh database and a five-versions-old one both end up
identical after ensure_schema() runs; nothing here ever edits a
migration that has already shipped.
"""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from typing import Iterator

from ..config import settings
from .migrations import MIGRATIONS

from jde_mcp_server import docstore

docstore.set_db_path_resolver(lambda: db_path())


def engine() -> str:
    """'postgres' when JDE_DATABASE_URL is set, else 'sqlite'."""
    return docstore.engine()


def db_path() -> str:
    """Read fresh every call (never cached at import time) so tests can
    monkeypatch settings.data_dir per test, exactly like every other
    store in this service already does."""
    override = os.environ.get("JDE_API_DB_PATH")
    if override:
        return override
    return os.path.join(settings.data_dir, "jde.sqlite3")


def get_connection():
    """A standalone connection with Jade's standard settings (WAL, foreign
    keys, a lock wait) -- see jde_mcp_server.docstore.connect."""
    return docstore.connect(db_path())


@contextmanager
def connection(*, immediate: bool = False) -> Iterator:
    """Commits on a clean exit, rolls back on an exception, always
    closes -- the pattern every service function in this module uses so
    none of them has to repeat it.

    This is the same transaction as the document store's
    (jde_mcp_server.docstore.transaction): inside an open transaction it
    joins it, so documents and tables written together commit or roll
    back together.

    immediate=True takes SQLite's write lock at the start (BEGIN
    IMMEDIATE), so a read-check-write sequence -- compare a revision,
    re-check the actor's authority, then write -- cannot interleave with
    another writer's."""
    with docstore.transaction(immediate=immediate, path=db_path()) as conn:
        yield conn


def _postgres_ddl(sql: str) -> str:
    """The migrations are written in the SQL both engines share; these are
    the few column-type spellings PostgreSQL writes differently."""
    import re

    sql = re.sub(r"INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    sql = re.sub(r"\bCOLLATE NOCASE\b", "", sql)
    sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
    sql = re.sub(r"\bBLOB\b", "BYTEA", sql)
    return sql


def ensure_schema() -> None:
    """Idempotent -- safe on every startup. Applies any migration not yet
    recorded in schema_migrations, in order, each one atomically: a
    migration either applies completely and is recorded, or not at all."""
    from datetime import datetime, timezone

    conn = get_connection()
    postgres = getattr(conn, "engine", "sqlite") == "postgres"
    try:
        conn.execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations ("
            "version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)"
        )
        conn.commit()
        if postgres:
            # One instance migrates at a time; the others wait, then find it done.
            conn.execute("SELECT pg_advisory_xact_lock(7302451000)")
        applied = {row[0] for row in conn.execute("SELECT version FROM schema_migrations")}
        for version, sql in MIGRATIONS:
            if version in applied:
                continue
            now = datetime.now(timezone.utc).isoformat()
            try:
                if postgres:
                    conn.executescript(_postgres_ddl(sql))
                    conn.execute("INSERT INTO schema_migrations (version, applied_at) VALUES (?, ?)", (int(version), now))
                else:
                    conn.executescript(
                        "BEGIN IMMEDIATE;\n" + sql + "\n;INSERT INTO schema_migrations (version, applied_at) "
                        f"VALUES ({int(version)}, '{now}');\nCOMMIT;"
                    )
            except Exception:
                if conn.in_transaction:
                    conn.rollback()
                raise
        if postgres:
            conn.commit()
    finally:
        conn.close()
